---
- name: Uninstall old versions
  ansible.builtin.dnf:
    name:
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
  become: true
- name: Install dnf-plugins-core to manage DNF repositories
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  become: true
- name: Set up docker repository
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  changed_when: true
  become: true
- name: Install the Docker packages
  ansible.builtin.dnf:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
- name: Configure automatical startup of Docker docker-engine
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
