---
- name: Uninstall conflicting packages
  ansible.builtin.shell: for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get -y remove $pkg; done
- name: Install ca-certificates
  ansible.builtin.apt:
    update_cache: true
    name:
      - ca-certificates
      - curl
- name: Install keyrings
  ansible.builtin.command: sudo install -m 0755 -d /etc/apt/keyrings
- name: Download docker gpg
  ansible.builtin.command: sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
- name: Modify mod
  ansible.builtin.command: sudo chmod a+r /etc/apt/keyrings/docker.asc
- name: Add the repository to apt sources
  ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
- name: Install the Docker packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
