---
- name: Converge
  hosts: all
  roles:
    - role: install-docker
  post_tasks:
    - name: Ensure docker is installed
      ansible.builtin.command: "docker run hello-world"
      register: result
      changed_when: false
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ result }}"
